version: 0.2
#Test


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 957814222158.dkr.ecr.ap-southeast-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecr-codebuild .
      - docker tag ecr-codebuild:latest 957814222158.dkr.ecr.ap-southeast-2.amazonaws.com/ecr-codebuild:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 957814222158.dkr.ecr.ap-southeast-2.amazonaws.com/ecr-codebuild:latest