version: 0.2
#Test


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 957814222158.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t codebuild-ecr .
      - docker tag codebuild-ecr:latest 957814222158.dkr.ecr.us-east-1.amazonaws.com/codebuild-ecr:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 957814222158.dkr.ecr.us-east-1.amazonaws.com/codebuild-ecr:latest